esdf_map_node:
  ros__parameters:

    # --- Robot inputs ---
    input_mode: "cloud"         # "robots" (default) or "cloud"

    bot_prefix: "bot"                    # "bot" -> bot1, bot2, ...
    bot_ids: [1,2,3,4]                         # robots that should be handled
    bot_cloud_topic: "cloud_registered"  # /botX/<this>
    bot_cloud_frame: "world"             # botX/<this> force cloud frame, if empty use `msg.header.frame_id`
    bot_sensor_frame: "lidar_link"       # botX/<this>  #TODO unused in simple core

    cloud_topic: "/global_downsampled_map"        # pcd topic
    cloud_frame: "map_origin"        # force cloud frame, if empty use `msg.header.frame_id`

    world_frame: "map_origin"        # global ESDF frame
    tf_timeout_sec: 0.1              # TF lookup timeout [s]

    # --- Map geometry (global ESDF grid in world_frame) ---
    esdf_resolution: 0.15             # [m] voxel size
    map_size_x: 22.0                 # [m]
    map_size_y: 17.0                 # [m]
    map_size_z: 6.0                  # [m]
    map_origin_x: -5.0               # [m]
    map_origin_y: -7.5               # [m]
    map_origin_z: 0.0                # [m]

    # --- TSDF / occupancy integration ---
    max_ray_length: 30.0             # [m] limit ray casting #TODO unused in simple core
    truncation_distance: 0.3         # [m] TSDF truncation band  #TODO unused in simple core
    esdf_max_distance: 5.0           # [m] clamp ESDF values
    enable_chamfer_relax: true       # enabple more accurate result

    # --- ESDF update strategy ---
    integrate_every_cloud: false     # update ESDF after every cloud
    esdf_update_rate_hz: 1.0         # used if integrate_every_cloud = false

    # --- Output / visualization ---
    publish_rate_hz: 1.0             # [Hz] publish grid & costmap
    publish_full_grid: true          # enable /esdf/grid
    publish_roi_grid: false          # enable /esdf/grid_roi - region of interenst (part that was updated)
    publish_costmap_2d: true         # enable /esdf/costmap_2d
    grid_max_distance: 1.0           # [m] only publish voxels with distance <= this (avoid red block in rviz)

    costmap_layer_z: 0.5             # [m] slice height in world_frame
    costmap_free_distance: 2.5       # [m] dist >= free -> cost=0
    costmap_lethal_distance: 0.25    # [m] dist <= lethal -> cost=100
    time_log: true                   # enable timing stats (avg/std over last 10s)
    debug_profile: false